try 9

diff --git a/.github/workflows/CI_CD.yaml b/.github/workflows/CI_CD.yaml
--- a/.github/workflows/CI_CD.yaml
+++ b/.github/workflows/CI_CD.yaml
@@ -11,44 +11,41 @@ jobs:
     runs-on: ostad1
 
     steps: 
-    - name: Code checkout
-      uses: actions/checkout@v3
-    
-    - name: Setup Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: 22
+      - name: Code checkout
+        uses: actions/checkout@v3
+      
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
 
-    - name: dependency install 
-      run: npm install
-    
-    - name: Run test & store log
-      run: |
-        
-        npm run check > results.txt || echo "TEST FAILD"
+      - name: Install dependencies
+        run: npm install
+      
+      - name: Run test & store log
+        run: |
+          mkdir -p test-results
+          npm run check > test-results/results.txt || echo "TEST FAILED"
 
-    - name: upload test results
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-results
-        path: test-results/results.txt
-
- #deploy
+      - name: Upload test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: test-results/results.txt
 
   deploy:
     runs-on: ostad1
     needs: test
 
     steps: 
-    - name: Code checkout
-      uses: actions/checkout@v3
+      - name: Code checkout
+        uses: actions/checkout@v3
 
-  
-    - name: Download test results
-      uses: actions/download-artifact@v4
-      with:
-        name: test-results
-    
+      - name: Download test results
+        uses: actions/download-artifact@v4
+        with:
+          name: test-results
+
 
 
     # services:
